=== aoeui/MMC/Markov/xml/Machine.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT machines (machine+)>
<!ELEMENT machine (state+)>
<!ATTLIST machine name CDATA #REQUIRED >
<!ELEMENT state (labels, decisionTree)>
<!ATTLIST state name CDATA #REQUIRED >
<!ELEMENT labels (labelPair+)>
<!ELEMENT labelPair (instance)>
<!ATTLIST labelPair name CDATA #REQUIRED > 
<!ELEMENT instance (#PCDATA)>
<!ELEMENT decisionTree (branch|probability)>
<!ELEMENT branch (predicate,consequent,alternative?)>
<!ELEMENT alternative (decisionTree)>
<!ELEMENT consequent (decisionTree)>
<!ELEMENT predicate ((or|and|neg|implies|atom))>
<!ELEMENT or (predicate,predicate+)>
<!ELEMENT and (predicate,predicate+)>
<!ELEMENT neg (predicate)>
<!ELEMENT implies (predicate,predicate)>
<!ELEMENT atom (labelPair)>
<!ATTLIST atom machineName CDATA #REQUIRED>
<!ELEMENT probability ((stateName,pValue)+)>
<!ELEMENT stateName (#PCDATA)>
<!ELEMENT pValue (#PCDATA)>

=== aoeui/MMC/Markov/xml/umlVersion2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE machines SYSTEM "Machine.dtd">
<machines>
  <machine name="M1">
<state name="q1">
<labels>
<labelPair name="1">
<instance>b</instance>
</labelPair>
<labelPair name="2">
<instance>c</instance>
</labelPair>
</labels>
<decisionTree> <branch>
<predicate>
<atom machineName="M2">
<labelPair name="1">
<instance>d</instance>
</labelPair>
</atom>
</predicate>
<consequent>
<decisionTree>
<branch>
<predicate>
<or>
<predicate>
<atom machineName="M2">
<labelPair name="2">
<instance>d</instance>
</labelPair>
</atom>
</predicate>
<predicate>
<atom machineName="M2">
<labelPair name="3">
<instance>d</instance>
</labelPair>
</atom>
</predicate>
</or>
</predicate>
<consequent>
<decisionTree>
<probability>
<stateName>1</stateName>
<pValue>1,3</pValue>
<stateName>2</stateName>
<pValue>2,3</pValue>
</probability>
</decisionTree>
</consequent>
<alternative>
<decisionTree>
<probability>
<stateName>2</stateName>
<pValue>1,1</pValue>
</probability>
</decisionTree>
</alternative>
</branch>
</decisionTree>
</consequent>
<alternative>
<decisionTree>
<branch>
<predicate>
<and>
<predicate>
<neg>
<predicate>
<atom machineName="M2">
<labelPair name="1">
<instance>e</instance>
</labelPair>
</atom>
</predicate>
</neg>
</predicate>
<predicate>
<implies>
<predicate>
<atom machineName="M2">
<labelPair name="1">
<instance>a</instance>
</labelPair>
</atom>
</predicate>
<predicate>
<atom machineName="M2">
<labelPair name="1">
<instance>b</instance>
</labelPair>
</atom>
</predicate>
</implies>
</predicate>
</and>
</predicate>
<consequent>
<decisionTree>
<probability>
<stateName>1</stateName>
<pValue>1,2</pValue>
<stateName>2</stateName>
<pValue>1,2</pValue>
</probability>
</decisionTree>
</consequent>
<alternative>
<decisionTree>
<probability>
<stateName>1</stateName>
<pValue>1,4</pValue>
<stateName>2</stateName>
<pValue>3,4</pValue>
</probability>
</decisionTree>
</alternative>
</branch>
</decisionTree>
</alternative>
</branch>
</decisionTree>
</state>
<state name="q2">
<labels>
<labelPair name="1">
<instance>d</instance>
</labelPair>
<labelPair name="2">
<instance>e</instance>
</labelPair>
</labels>
<decisionTree> <branch>
<predicate>
<atom machineName="M2">
<labelPair name="1">
<instance>d</instance>
</labelPair>
</atom>
</predicate>
<consequent>
<decisionTree>
<branch>
<predicate>
<or>
<predicate>
<atom machineName="M2">
<labelPair name="2">
<instance>d</instance>
</labelPair>
</atom>
</predicate>
<predicate>
<atom machineName="M2">
<labelPair name="3">
<instance>d</instance>
</labelPair>
</atom>
</predicate>
</or>
</predicate>
<consequent>
<decisionTree>
<probability>
<stateName>1</stateName>
<pValue>1,3</pValue>
<stateName>2</stateName>
<pValue>2,3</pValue>
</probability>
</decisionTree>
</consequent>
<alternative>
<decisionTree>
<probability>
<stateName>2</stateName>
<pValue>1,1</pValue>
</probability>
</decisionTree>
</alternative>
</branch>
</decisionTree>
</consequent>
<alternative>
<decisionTree>
<branch>
<predicate>
<and>
<predicate>
<atom machineName="M2">
<labelPair name="1">
<instance>e</instance>
</labelPair>
</atom>
</predicate>
<predicate>
<atom machineName="M2">
<labelPair name="1">
<instance>a</instance>
</labelPair>
</atom>
</predicate>
<predicate>
<or>
<predicate>
<atom machineName="M2">
<labelPair name="1">
<instance>b</instance>
</labelPair>
</atom>
</predicate>
<predicate>
<atom machineName="M2">
<labelPair name="1">
<instance>c</instance>
</labelPair>
</atom>
</predicate>
<predicate>
<atom machineName="M2">
<labelPair name="2">
<instance>c</instance>
</labelPair>
</atom>
</predicate>
</or>
</predicate>
</and>
</predicate>
<consequent>
<decisionTree>
<probability>
<stateName>1</stateName>
<pValue>1,2</pValue>
<stateName>2</stateName>
<pValue>1,2</pValue>
</probability>
</decisionTree>
</consequent>
<alternative>
<decisionTree>
<probability>
<stateName>1</stateName>
<pValue>1,4</pValue>
<stateName>2</stateName>
<pValue>3,4</pValue>
</probability>
</decisionTree>
</alternative>
</branch>
</decisionTree>
</alternative>
</branch>
</decisionTree>
</state>
</machine>
  <machine name="M2">
<state name="q1">
<labels>
<labelPair name="1">
<instance>c</instance>
</labelPair>
<labelPair name="2">
<instance>b</instance>
</labelPair>
<labelPair name="3">
<instance>e</instance>
</labelPair>
</labels>
<decisionTree> <branch>
<predicate>
<atom machineName="M1">
<labelPair name="1">
<instance>d</instance>
</labelPair>
</atom>
</predicate>
<consequent>
<decisionTree>
<branch>
<predicate>
<or>
<predicate>
<atom machineName="M1">
<labelPair name="2">
<instance>d</instance>
</labelPair>
</atom>
</predicate>
<predicate>
<atom machineName="M1">
<labelPair name="2">
<instance>d</instance>
</labelPair>
</atom>
</predicate>
</or>
</predicate>
<consequent>
<decisionTree>
<probability>
<stateName>1</stateName>
<pValue>1,3</pValue>
<stateName>2</stateName>
<pValue>2,3</pValue>
</probability>
</decisionTree>
</consequent>
<alternative>
<decisionTree>
<probability>
<stateName>2</stateName>
<pValue>1,1</pValue>
</probability>
</decisionTree>
</alternative>
</branch>
</decisionTree>
</consequent>
<alternative>
<decisionTree>
<branch>
<predicate>
<atom machineName="M1">
<labelPair name="1">
<instance>e</instance>
</labelPair>
</atom>
</predicate>
<consequent>
<decisionTree>
<probability>
<stateName>1</stateName>
<pValue>1,2</pValue>
<stateName>2</stateName>
<pValue>1,2</pValue>
</probability>
</decisionTree>
</consequent>
<alternative>
<decisionTree>
<probability>
<stateName>1</stateName>
<pValue>1,4</pValue>
<stateName>2</stateName>
<pValue>3,4</pValue>
</probability>
</decisionTree>
</alternative>
</branch>
</decisionTree>
</alternative>
</branch>
</decisionTree>
</state>
<state name="q2">
<labels>
<labelPair name="1">
<instance>a</instance>
</labelPair>
<labelPair name="2">
<instance>c</instance>
</labelPair>
<labelPair name="3">
<instance>d</instance>
</labelPair>
</labels>
<decisionTree> <branch>
<predicate>
<atom machineName="M1">
<labelPair name="1">
<instance>e</instance>
</labelPair>
</atom>
</predicate>
<consequent>
<decisionTree>
<branch>
<predicate>
<or>
<predicate>
<atom machineName="M1">
<labelPair name="2">
<instance>f</instance>
</labelPair>
</atom>
</predicate>
<predicate>
<atom machineName="M1">
<labelPair name="2">
<instance>e</instance>
</labelPair>
</atom>
</predicate>
</or>
</predicate>
<consequent>
<decisionTree>
<probability>
<stateName>1</stateName>
<pValue>1,3</pValue>
<stateName>2</stateName>
<pValue>2,3</pValue>
</probability>
</decisionTree>
</consequent>
<alternative>
<decisionTree>
<probability>
<stateName>2</stateName>
<pValue>1,1</pValue>
</probability>
</decisionTree>
</alternative>
</branch>
</decisionTree>
</consequent>
<alternative>
<decisionTree>
<branch>
<predicate>
<atom machineName="M1">
<labelPair name="1">
<instance>a</instance>
</labelPair>
</atom>
</predicate>
<consequent>
<decisionTree>
<probability>
<stateName>1</stateName>
<pValue>1,2</pValue>
<stateName>3</stateName>
<pValue>1,2</pValue>
</probability>
</decisionTree>
</consequent>
<alternative>
<decisionTree>
<probability>
<stateName>3</stateName>
<pValue>1,4</pValue>
<stateName>2</stateName>
<pValue>3,4</pValue>
</probability>
</decisionTree>
</alternative>
</branch>
</decisionTree>
</alternative>
</branch>
</decisionTree>
</state>
<state name="q3">
<labels>
<labelPair name="1">
<instance>b</instance>
</labelPair>
<labelPair name="2">
<instance>c</instance>
</labelPair>
<labelPair name="3">
<instance>a</instance>
</labelPair>
</labels>
<decisionTree> <branch>
<predicate>
<atom machineName="M1">
<labelPair name="1">
<instance>d</instance>
</labelPair>
</atom>
</predicate>
<consequent>
<decisionTree>
<branch>
<predicate>
<or>
<predicate>
<atom machineName="M1">
<labelPair name="2">
<instance>d</instance>
</labelPair>
</atom>
</predicate>
<predicate>
<atom machineName="M1">
<labelPair name="2">
<instance>e</instance>
</labelPair>
</atom>
</predicate>
</or>
</predicate>
<consequent>
<decisionTree>
<probability>
<stateName>1</stateName>
<pValue>1,3</pValue>
<stateName>3</stateName>
<pValue>2,3</pValue>
</probability>
</decisionTree>
</consequent>
<alternative>
<decisionTree>
<probability>
<stateName>1</stateName>
<pValue>1,1</pValue>
</probability>
</decisionTree>
</alternative>
</branch>
</decisionTree>
</consequent>
<alternative>
<decisionTree>
<branch>
<predicate>
<atom machineName="M1">
<labelPair name="1">
<instance>e</instance>
</labelPair>
</atom>
</predicate>
<consequent>
<decisionTree>
<probability>
<stateName>3</stateName>
<pValue>1,2</pValue>
<stateName>1</stateName>
<pValue>1,2</pValue>
</probability>
</decisionTree>
</consequent>
<alternative>
<decisionTree>
<probability>
<stateName>1</stateName>
<pValue>1,4</pValue>
<stateName>3</stateName>
<pValue>3,4</pValue>
</probability>
</decisionTree>
</alternative>
</branch>
</decisionTree>
</alternative>
</branch>
</decisionTree>
</state>
</machine>
</machines>

=== aoeui/MMC/Markov/xml/umlVersion5.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE machines SYSTEM "Machine.dtd">
<machines>
  <machine name="MPatient:ICP"><state name="InitLow"><labels><labelPair name="Cost"><instance>10000</instance></labelPair><labelPair name="Patient"><instance>G</instance></labelPair><labelPair name="ICP"><instance>A</instance></labelPair></labels><decisionTree><probability><stateName>InitLow</stateName><pValue>65,100</pValue><stateName>High</stateName><pValue>1,10</pValue><stateName>Dead</stateName><pValue>5,100</pValue><stateName>Exit</stateName><pValue>2,10</pValue></probability></decisionTree></state><state name="High"><labels><labelPair name="Cost"><instance>20000</instance></labelPair><labelPair name="Patient"><instance>B</instance></labelPair><labelPair name="ICP"><instance>B</instance></labelPair></labels><decisionTree><probability><stateName>High</stateName><pValue>5,10</pValue><stateName>Low</stateName><pValue>35,100</pValue><stateName>Dead</stateName><pValue>15,100</pValue></probability></decisionTree></state><state name="Exit"><labels><labelPair name="Cost"><instance>3000</instance></labelPair><labelPair name="Patient"><instance>G</instance></labelPair><labelPair name="ICP"><instance>E</instance></labelPair></labels><decisionTree><probability><stateName>Exit</stateName><pValue>1,1</pValue></probability></decisionTree></state><state name="Dead"><labels><labelPair name="Cost"><instance>25000</instance></labelPair><labelPair name="Patient"><instance>NA</instance></labelPair><labelPair name="ICP"><instance>D</instance></labelPair></labels><decisionTree><probability><stateName>Dead</stateName><pValue>1,1</pValue></probability></decisionTree></state><state name="Low"><labels><labelPair name="Cost"><instance>6000</instance></labelPair><labelPair name="Patient"><instance>G</instance></labelPair><labelPair name="ICP"><instance>C</instance></labelPair></labels><decisionTree><probability><stateName>High</stateName><pValue>5,100</pValue><stateName>Low</stateName><pValue>5,10</pValue><stateName>Dead</stateName><pValue>5,100</pValue><stateName>Exit</stateName><pValue>4,10</pValue></probability></decisionTree></state></machine>
</machines>

=== aoeui/MMC/Markov/xml/Machine.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE machines SYSTEM "Machine.dtd">
<machines>
	<machine name="1020103">
    	<state name="103020">
        	<labels>
				<labelPair name="1030201">
					<instance>b</instance>
				</labelPair>
				<labelPair name="102301">
					<instance>c</instance>
				</labelPair>
			</labels>
			<decisionTree>
				<branch>
					<predicate>
						<atom machineName="103024">
							<labelPair name="1030929">
							  <instance>d</instance>
							</labelPair>
						</atom>
					</predicate>
					<consequent>
						<decisionTree>
							<branch>
								<predicate>
									<or>
										<predicate>
											<atom machineName="103024">
												<labelPair name="1030929">
							  						<instance>d</instance>
												</labelPair>
											</atom>
										</predicate>
										<predicate>
											<atom machineName="103022">
												<labelPair name="1030949">
								  					<instance>d</instance>
												</labelPair>
											</atom>
										</predicate>
									</or>
								</predicate>
								<consequent>
									<decisionTree>
										<probability>
											<instance>c</instance>
											<pValue>0.01203</pValue>
										</probability>
									</decisionTree>							
								</consequent>
							</branch>
						</decisionTree>
					</consequent>
					<alternative>
						<decisionTree>
							<branch>
								<predicate>
									<atom machineName="103024">
										<labelPair name="1030929">
											<instance>d</instance>
										</labelPair>
									</atom>
								</predicate>
								<consequent>
									<decisionTree>					
										<probability>
											<instance>c</instance>
											<pValue>0.01203</pValue>
										</probability>
									</decisionTree>
								</consequent>
							</branch>
						</decisionTree>
					</alternative>						
				</branch>				
			</decisionTree>
		</state>
	</machine>
</machines>
